select  all SMS_R_System.Netbios_Name0 as Name
--,SMS_GH_System_WINDOWSUPDATE.UseWUServer00
--,max(__stem_QUICK_FIX_ENGINEERING0.HotFixID00)
,max(__stem_QUICK_FIX_ENGINEERING0.InstalledOn00) as MaxDateInstalled
--,__stem_QUICK_FIX_ENGINEERING0.TimeKey 
from vSMS_R_System AS SMS_R_System 
INNER JOIN WINDOWSUPDATE_HIST AS SMS_GH_System_WINDOWSUPDATE ON SMS_GH_System_WINDOWSUPDATE.MachineID = SMS_R_System.ItemKey  
INNER JOIN QUICK_FIX_ENGINEERING_DATA AS __stem_QUICK_FIX_ENGINEERING0 ON __stem_QUICK_FIX_ENGINEERING0.MachineID = SMS_R_System.ItemKey   
--OPTION(USE HINT('FORCE_LEGACY_CARDINALITY_ESTIMATION'))
group by SMS_R_System.Netbios_Name0--, __stem_QUICK_FIX_ENGINEERING0.InstalledOn00,  __stem_QUICK_FIX_ENGINEERING0.HotFixID00
order by Name