---
  - name: Create Folder One
    file:
     path: /home/secret/folder1
     state: directory
     mode: 0755

  - name: Create Folder Two
    file:
     path: /home/secret/folder2
     state: directory
     mode: 0755

