---
- name: My Include Playbook
  hosts: all
  become: yes

  vars:
    mytext: "Hi World!"
  tasks:
  - name: Ping test
    ping:

  - name: Crete Folder
    include: createfolder.yml 
 
  - name: Create Files
    include: createfile.yml mytext="second var value"


