---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes
 
  vars:
    source_file: ./index.html
    destin_file: /var/www/html

  tasks:
  - name: Check and Print linux version
    debug: var=ansible_os_family

  - block: # ======  Block for Redhat ===== 

     - name: Install Apache Web Server for Redhat
       yum: name=httpd state=latest
      
     - name: Copy me webpage to servers
       copy: src={{ source_file }} dest={{ destin_file }} mode=0555
       notify: Restart Apache Redhat 

     - name: Start Web Server and Enable it on the boot Redhat
       service: name=httpd state=started enabled=yes
     
    when: ansible_os_family == "RedHat"

  - block: # ====== Block for Debian ======
 
     - name: Install Apache Web Server for Ubuntu
       apt: name=apache2 state=latest update_cache=yes
    
     - name: Copy me webpage to servers
       copy: src={{ source_file }} dest={{ destin_file }} mode=0555
       notify: Restart Apache Debian

     - name: Start Web Server and Enable it on the boot Debian
       service: name=apache2 state=started enabled=yes
      
    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache Redhat
    service: name=httpd state=restarted

  - name: Restart Apache Debian
    service: name=apache2 state=restarted
